/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i widget_adaptor.h -a :widget_adaptor.cpp ../../qtcontroller/light/widget.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "widget_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class WidgetAdaptor
 */

WidgetAdaptor::WidgetAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

WidgetAdaptor::~WidgetAdaptor()
{
    // destructor
}

bool WidgetAdaptor::mIsOn() const
{
    // get the value of property mIsOn
    return qvariant_cast< bool >(parent()->property("mIsOn"));
}

void WidgetAdaptor::setMIsOn(bool value)
{
    // set the value of property mIsOn
    parent()->setProperty("mIsOn", QVariant::fromValue(value));
}

void WidgetAdaptor::turnOff()
{
    // handle method call tlp.local.widget.turnOff
    QMetaObject::invokeMethod(parent(), "turnOff");
}

void WidgetAdaptor::turnOn()
{
    // handle method call tlp.local.widget.turnOn
    QMetaObject::invokeMethod(parent(), "turnOn");
}

