/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a widget_adaptor.h: ../../qtcontroller/light/widget.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef WIDGET_ADAPTOR_H
#define WIDGET_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface tlp.local.widget
 */
class WidgetAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "tlp.local.widget")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"tlp.local.widget\">\n"
"    <property access=\"readwrite\" type=\"b\" name=\"mIsOn\"/>\n"
"    <signal name=\"lightChanged\"/>\n"
"    <method name=\"turnOn\"/>\n"
"    <method name=\"turnOff\"/>\n"
"  </interface>\n"
        "")
public:
    WidgetAdaptor(QObject *parent);
    virtual ~WidgetAdaptor();

public: // PROPERTIES
    Q_PROPERTY(bool mIsOn READ mIsOn WRITE setMIsOn)
    bool mIsOn() const;
    void setMIsOn(bool value);

public Q_SLOTS: // METHODS
    void turnOff();
    void turnOn();
Q_SIGNALS: // SIGNALS
    void lightChanged();
};

#endif
